### ISSUE TITLE
Redirect from master to main does not the SEO issue with contribution_guide.html

### ISSUE THREAD

**Issue by svekars** [pytorch/docs#12]
We need to unlist this page in Google: https://pytorch.org/docs/master/community/contribution_guide.html which is at the moment, the first result and appears like this:
<img width="603" alt="Screenshot 2024-09-06 at 3 41 38 PM" src="https://github.com/user-attachments/assets/53cd76ac-ff03-4af3-88ea-283e8ff7fedd">

I have first proposed to add the noindex tag with this PR: https://github.com/pytorch/docs/pull/10 

Then according to Google's recommendations, I proposed to disable the Dissalow rule for master in robots.txt: 
https://github.com/pytorch/pytorch.github.io/pull/1723

However, a better solution was proposed by @malfet to create a symlink to redirect master to main, which we [implemented](https://github.com/pytorch/docs/pull/11).

However, this solution presents issues with the user experience:

* Although we redirect master to main and the correct page is displayed, in the path, there is still `master` (which can be confusing to the users)
*  https://pytorch.org/docs/master/community/contribution_guide.html is still the first result in Google and even though it forwards to the correct link, there is no description to that page. Ideally, we want Google to forget that page and learn to forward to main or stable.

**Comment by malfet** [comment]
We can revive a master folder but populate with scripts that return HTTP/301 and point to the new location

**Comment by malfet** [comment]
And if I understand how Google search work it would prefer redirects in favor of full pages

**Comment by svekars** [comment]
Closing with this: https://github.com/pytorch/docs/pull/14
